# Generated by Django 4.2.9 on 2025-11-25 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='from_code',
            field=models.CharField(default='00000', help_text='Mã nhóm 5 số', max_length=5, verbose_name='Nhóm hiện tại'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='to_code',
            field=models.CharField(default='00000', help_text='Mã nhóm 5 số', max_length=5, verbose_name='Nhóm chuyển đến'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='effective_date',
            field=models.DateField(verbose_name='Ngày hiệu lực'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='from_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='transfer_app.group'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='Chuyển cố định'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='msnv',
            field=models.CharField(max_length=50, verbose_name='MSNV'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do từ chối'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('CONFIRMED', 'Đã xác nhận'), ('REJECTED', 'Từ chối'), ('CANCELED', 'Hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='transfer_app.group'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc'),
        ),
    ]
