# Generated by Django 4.2.9 on 2025-11-25 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer_app', '0002_transferrequest_from_code_transferrequest_to_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Duyệt lúc'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hủy lúc'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_canceled', to=settings.AUTH_USER_MODEL, verbose_name='Người hủy'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Xác nhận lúc'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Từ chối lúc'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_rejected', to=settings.AUTH_USER_MODEL, verbose_name='Người từ chối'),
        ),
    ]
