# Generated by Django 4.2.9 on 2025-11-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0005_batch_designated_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do chuyển đổi'),
        ),
    ]
